-- MySQL Script generated by MySQL Workbench
-- 12/07/18 08:43:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema FreeGo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FreeGo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FreeGo` DEFAULT CHARACTER SET utf8 ;
USE `FreeGo` ;

-- -----------------------------------------------------
-- Table `FreeGo`.`Fridge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeGo`.`Fridge` ;

CREATE TABLE IF NOT EXISTS `FreeGo`.`Fridge` (
  `IdFridge` INT NOT NULL,
  PRIMARY KEY (`IdFridge`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeGo`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeGo`.`User` ;

CREATE TABLE IF NOT EXISTS `FreeGo`.`User` (
  `IdUser` INT NOT NULL,
  `UserName` VARCHAR(45) NULL,
  `UserEmail` VARCHAR(45) NULL,
  `UserPassword` VARCHAR(45) NULL,
  `Fridge_IdFridge` INT NOT NULL,
  PRIMARY KEY (`IdUser`),
  INDEX `fk_User_Fridge1_idx` (`Fridge_IdFridge` ASC),
  CONSTRAINT `fk_User_Fridge1`
    FOREIGN KEY (`Fridge_IdFridge`)
    REFERENCES `FreeGo`.`Fridge` (`IdFridge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeGo`.`ShoppingList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeGo`.`ShoppingList` ;

CREATE TABLE IF NOT EXISTS `FreeGo`.`ShoppingList` (
  `IdShoppingList` INT NOT NULL,
  `Fridge_IdFridge` INT NOT NULL,
  PRIMARY KEY (`IdShoppingList`, `Fridge_IdFridge`),
  INDEX `fk_ShoppingList_Fridge1_idx` (`Fridge_IdFridge` ASC),
  CONSTRAINT `fk_ShoppingList_Fridge1`
    FOREIGN KEY (`Fridge_IdFridge`)
    REFERENCES `FreeGo`.`Fridge` (`IdFridge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeGo`.`Ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeGo`.`Ingredients` ;

CREATE TABLE IF NOT EXISTS `FreeGo`.`Ingredients` (
  `IdIngredients` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `ExpirationDate` DATE NULL,
  `Quantity` INT NULL,
  `Unit` VARCHAR(45) NULL,
  PRIMARY KEY (`IdIngredients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeGo`.`UserListeForFridge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeGo`.`UserListeForFridge` ;

CREATE TABLE IF NOT EXISTS `FreeGo`.`UserListeForFridge` (
  `Fk_IdUser` INT NOT NULL,
  `Fk_IdFridge` INT NOT NULL,
  PRIMARY KEY (`Fk_IdUser`, `Fk_IdFridge`),
  INDEX `fk_User_has_Fridge_Fridge1_idx` (`Fk_IdFridge` ASC),
  INDEX `fk_User_has_Fridge_User_idx` (`Fk_IdUser` ASC),
  CONSTRAINT `fk_User_has_Fridge_User`
    FOREIGN KEY (`Fk_IdUser`)
    REFERENCES `FreeGo`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Fridge_Fridge1`
    FOREIGN KEY (`Fk_IdFridge`)
    REFERENCES `FreeGo`.`Fridge` (`IdFridge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeGo`.`IngredientsListForFridge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeGo`.`IngredientsListForFridge` ;

CREATE TABLE IF NOT EXISTS `FreeGo`.`IngredientsListForFridge` (
  `Fk_IdIngredients` INT NOT NULL,
  `Fk_IdFridge` INT NOT NULL,
  PRIMARY KEY (`Fk_IdIngredients`, `Fk_IdFridge`),
  INDEX `fk_Ingredients_has_Fridge_Fridge1_idx` (`Fk_IdFridge` ASC),
  INDEX `fk_Ingredients_has_Fridge_Ingredients1_idx` (`Fk_IdIngredients` ASC),
  CONSTRAINT `fk_Ingredients_has_Fridge_Ingredients1`
    FOREIGN KEY (`Fk_IdIngredients`)
    REFERENCES `FreeGo`.`Ingredients` (`IdIngredients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingredients_has_Fridge_Fridge1`
    FOREIGN KEY (`Fk_IdFridge`)
    REFERENCES `FreeGo`.`Fridge` (`IdFridge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeGo`.`IngredientsListInFridge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeGo`.`IngredientsListInFridge` ;

CREATE TABLE IF NOT EXISTS `FreeGo`.`IngredientsListInFridge` (
  `Fk_IdFridge` INT NOT NULL,
  `Fk_IdIngredients` INT NOT NULL,
  `Quantity` INT NULL,
  `Unit` VARCHAR(45) NULL,
  `Limit` SMALLINT NULL,
  PRIMARY KEY (`Fk_IdFridge`, `Fk_IdIngredients`),
  INDEX `fk_Fridge_has_Ingredients_Ingredients1_idx` (`Fk_IdIngredients` ASC),
  INDEX `fk_Fridge_has_Ingredients_Fridge1_idx` (`Fk_IdFridge` ASC),
  CONSTRAINT `fk_Fridge_has_Ingredients_Fridge1`
    FOREIGN KEY (`Fk_IdFridge`)
    REFERENCES `FreeGo`.`Fridge` (`IdFridge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fridge_has_Ingredients_Ingredients1`
    FOREIGN KEY (`Fk_IdIngredients`)
    REFERENCES `FreeGo`.`Ingredients` (`IdIngredients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeGo`.`IngredientsInShoppingList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeGo`.`IngredientsInShoppingList` ;

CREATE TABLE IF NOT EXISTS `FreeGo`.`IngredientsInShoppingList` (
  `Fk_IdShoppingList` INT NOT NULL,
  `Fk_IdIngredients` INT NOT NULL,
  `Quantity` INT NULL,
  `Unit` VARCHAR(45) NULL,
  PRIMARY KEY (`Fk_IdShoppingList`, `Fk_IdIngredients`),
  INDEX `fk_ShoppingList_has_Ingredients_Ingredients1_idx` (`Fk_IdIngredients` ASC),
  INDEX `fk_ShoppingList_has_Ingredients_ShoppingList1_idx` (`Fk_IdShoppingList` ASC),
  CONSTRAINT `fk_ShoppingList_has_Ingredients_ShoppingList1`
    FOREIGN KEY (`Fk_IdShoppingList`)
    REFERENCES `FreeGo`.`ShoppingList` (`IdShoppingList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ShoppingList_has_Ingredients_Ingredients1`
    FOREIGN KEY (`Fk_IdIngredients`)
    REFERENCES `FreeGo`.`Ingredients` (`IdIngredients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
