-- MySQL Script generated by MySQL Workbench
-- 11/23/18 08:14:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema FreeGo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FreeGo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FreeGo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `FreeGo` ;

-- -----------------------------------------------------
-- Table `FreeGo`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeGo`.`User` ;

CREATE TABLE IF NOT EXISTS `FreeGo`.`User` (
  `IdUser` INT NOT NULL COMMENT '',
  `UserName` VARCHAR(45) NULL COMMENT '',
  `UserEmail` VARCHAR(45) NULL COMMENT '',
  `UserPassword` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`IdUser`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeGo`.`Fridge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeGo`.`Fridge` ;

CREATE TABLE IF NOT EXISTS `FreeGo`.`Fridge` (
  `IdFridge` INT NOT NULL COMMENT '',
  PRIMARY KEY (`IdFridge`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeGo`.`ShoppingList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeGo`.`ShoppingList` ;

CREATE TABLE IF NOT EXISTS `FreeGo`.`ShoppingList` (
  `IdShoppingList` INT NOT NULL COMMENT '',
  `Fridge_IdFridge` INT NOT NULL COMMENT '',
  PRIMARY KEY (`IdShoppingList`, `Fridge_IdFridge`)  COMMENT '',
  INDEX `fk_ShoppingList_Fridge1_idx` (`Fridge_IdFridge` ASC)  COMMENT '',
  CONSTRAINT `fk_ShoppingList_Fridge1`
    FOREIGN KEY (`Fridge_IdFridge`)
    REFERENCES `FreeGo`.`Fridge` (`IdFridge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeGo`.`Ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeGo`.`Ingredients` ;

CREATE TABLE IF NOT EXISTS `FreeGo`.`Ingredients` (
  `IdIngredients` INT NOT NULL COMMENT '',
  `Nom` VARCHAR(45) NULL COMMENT '',
  `ExpirationDate` DATE NULL COMMENT '',
  `Quantity` INT NULL COMMENT '',
  `Unit` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`IdIngredients`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeGo`.`UserListeForFridge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeGo`.`UserListeForFridge` ;

CREATE TABLE IF NOT EXISTS `FreeGo`.`UserListeForFridge` (
  `Fk_IdUser` INT NOT NULL COMMENT '',
  `Fk_IdFridge` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Fk_IdUser`, `Fk_IdFridge`)  COMMENT '',
  INDEX `fk_User_has_Fridge_Fridge1_idx` (`Fk_IdFridge` ASC)  COMMENT '',
  INDEX `fk_User_has_Fridge_User_idx` (`Fk_IdUser` ASC)  COMMENT '',
  CONSTRAINT `fk_User_has_Fridge_User`
    FOREIGN KEY (`Fk_IdUser`)
    REFERENCES `FreeGo`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Fridge_Fridge1`
    FOREIGN KEY (`Fk_IdFridge`)
    REFERENCES `FreeGo`.`Fridge` (`IdFridge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeGo`.`IngredientsListForFridge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeGo`.`IngredientsListForFridge` ;

CREATE TABLE IF NOT EXISTS `FreeGo`.`IngredientsListForFridge` (
  `Fk_IdIngredients` INT NOT NULL COMMENT '',
  `Fk_IdFridge` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Fk_IdIngredients`, `Fk_IdFridge`)  COMMENT '',
  INDEX `fk_Ingredients_has_Fridge_Fridge1_idx` (`Fk_IdFridge` ASC)  COMMENT '',
  INDEX `fk_Ingredients_has_Fridge_Ingredients1_idx` (`Fk_IdIngredients` ASC)  COMMENT '',
  CONSTRAINT `fk_Ingredients_has_Fridge_Ingredients1`
    FOREIGN KEY (`Fk_IdIngredients`)
    REFERENCES `FreeGo`.`Ingredients` (`IdIngredients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingredients_has_Fridge_Fridge1`
    FOREIGN KEY (`Fk_IdFridge`)
    REFERENCES `FreeGo`.`Fridge` (`IdFridge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeGo`.`IngredientsListInFridge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeGo`.`IngredientsListInFridge` ;

CREATE TABLE IF NOT EXISTS `FreeGo`.`IngredientsListInFridge` (
  `Fk_IdFridge` INT NOT NULL COMMENT '',
  `Fk_IdIngredients` INT NOT NULL COMMENT '',
  `Quantity` INT NULL COMMENT '',
  `Unit` VARCHAR(45) NULL COMMENT '',
  `Limit` SMALLINT NULL COMMENT '',
  PRIMARY KEY (`Fk_IdFridge`, `Fk_IdIngredients`)  COMMENT '',
  INDEX `fk_Fridge_has_Ingredients_Ingredients1_idx` (`Fk_IdIngredients` ASC)  COMMENT '',
  INDEX `fk_Fridge_has_Ingredients_Fridge1_idx` (`Fk_IdFridge` ASC)  COMMENT '',
  CONSTRAINT `fk_Fridge_has_Ingredients_Fridge1`
    FOREIGN KEY (`Fk_IdFridge`)
    REFERENCES `FreeGo`.`Fridge` (`IdFridge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fridge_has_Ingredients_Ingredients1`
    FOREIGN KEY (`Fk_IdIngredients`)
    REFERENCES `FreeGo`.`Ingredients` (`IdIngredients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeGo`.`IngredientsInShoppingList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeGo`.`IngredientsInShoppingList` ;

CREATE TABLE IF NOT EXISTS `FreeGo`.`IngredientsInShoppingList` (
  `Fk_IdShoppingList` INT NOT NULL COMMENT '',
  `Fk_IdIngredients` INT NOT NULL COMMENT '',
  `Quantity` INT NULL COMMENT '',
  `Unit` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`Fk_IdShoppingList`, `Fk_IdIngredients`)  COMMENT '',
  INDEX `fk_ShoppingList_has_Ingredients_Ingredients1_idx` (`Fk_IdIngredients` ASC)  COMMENT '',
  INDEX `fk_ShoppingList_has_Ingredients_ShoppingList1_idx` (`Fk_IdShoppingList` ASC)  COMMENT '',
  CONSTRAINT `fk_ShoppingList_has_Ingredients_ShoppingList1`
    FOREIGN KEY (`Fk_IdShoppingList`)
    REFERENCES `FreeGo`.`ShoppingList` (`IdShoppingList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ShoppingList_has_Ingredients_Ingredients1`
    FOREIGN KEY (`Fk_IdIngredients`)
    REFERENCES `FreeGo`.`Ingredients` (`IdIngredients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
